default_language_version:
  node: default
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: ['--target-version', 'py37']
  - repo: https://github.com/timothycrosley/isort
    # isort config is in setup.cfg
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-assertive
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [css, scss, javascript, ts, tsx, json, yaml]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.36.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(js|ts|tsx)$
        args: [--report-unused-disable-directives]
        additional_dependencies:
          - eslint@8.8.0
          - '@typescript-eslint/eslint-plugin@5.10.1'
          - '@typescript-eslint/parser@5.10.1'
          - '@wagtail/eslint-config-wagtail@0.4.0'
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v15.2.0
    hooks:
      - id: stylelint
        files: \.scss$
        additional_dependencies:
          - stylelint@14.2.0
          - '@wagtail/stylelint-config-wagtail@0.3.2'
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        args: ['--parse-only']
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.5
    hooks:
      - id: djhtml
  # - repo: https://github.com/returntocorp/semgrep
  #   rev: v1.14.0
  #   hooks:
  #     - id: semgrep
  #       args: ['--config', '.semgrep.yml', '--error']
